import type { Drink } from "./types";

export const drinks: Drink[] = [
  {
    id: "cocktail-1",
    name: "Whiskey Sour",
    price: 10000,
    currency: "NGN",
    description:
      "Classic whiskey cocktail with fresh lemon juice and simple syrup",
    category: "cocktails",
    image: "/whiskey-sour-cocktail.jpg",
    tags: ["Cocktail", "Classic"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "cocktail-2",
    name: "Margarita",
    price: 10000,
    currency: "NGN",
    description: "Tequila, lime juice, and orange liqueur served chilled",
    category: "cocktails",
    image: "/margarita-cocktail.png",
    tags: ["Cocktail", "Classic"],
    popular: true,
    availableIn: ["club", "office"],
  },
  {
    id: "cocktail-3",
    name: "Mojito",
    price: 10000,
    currency: "NGN",
    description: "Refreshing blend of white rum, mint, lime, sugar, and soda",
    category: "cocktails",
    image: "/mojito-cocktail-with-mint.jpg",
    tags: ["Cocktail", "Classic"],
    popular: true,
    availableIn: ["club", "office"],
  },
  {
    id: "cocktail-4",
    name: "Long Island",
    price: 12000,
    currency: "NGN",
    description: "Bold mix of multiple spirits with cola and citrus notes",
    category: "cocktails",
    image: "/long-island-iced-tea.jpg",
    tags: ["Cocktail", "Classic"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "cocktail-5",
    name: "Old Fashioned",
    price: 12000,
    currency: "NGN",
    description: "Timeless whiskey cocktail with bitters and sugar",
    category: "cocktails",
    image: "/old-fashioned-cocktail.png",
    tags: ["Cocktail", "Classic"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "cocktail-6",
    name: "Pornstar Martini",
    price: 10000,
    currency: "NGN",
    description: "Vodka, passion fruit liqueur, vanilla, and passion fruit",
    category: "cocktails",
    image: "/pornstar-martini-passion-fruit.jpg",
    tags: ["Cocktail", "Classic"],
    popular: true,
    availableIn: ["club", "office"],
  },
  {
    id: "cocktail-7",
    name: "Classic Martini",
    price: 10000,
    currency: "NGN",
    description: "Gin and dry vermouth, garnished with an olive or lemon twist",
    category: "cocktails",
    image: "/classic-martini-cocktail.jpg",
    tags: ["Cocktail", "Classic"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "cocktail-8",
    name: "Bellini",
    price: 10000,
    currency: "NGN",
    description: "Prosecco and peach purée",
    category: "cocktails",
    image: "/bellini-peach-cocktail.jpg",
    tags: ["Cocktail", "Classic"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "signature-cocktail-1",
    name: "Atlantic Cocktail",
    price: 150000,
    currency: "NGN",
    description: "Premium signature cocktail with exotic ingredients",
    category: "signature-cocktails",
    image: "/luxury-premium-cocktail.jpg",
    tags: ["Signature", "Premium"],
    popular: true,
    availableIn: ["club", "office"],
  },
  {
    id: "signature-cocktail-2",
    name: "The Century",
    price: 12000,
    currency: "NGN",
    description: "Signature blend celebrating timeless flavors",
    category: "signature-cocktails",
    image: "/signature-cocktail-gold.jpg",
    tags: ["Signature"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "signature-cocktail-3",
    name: "Apple Savanna",
    price: 12000,
    currency: "NGN",
    description: "Fresh apple infusion with savanna notes",
    category: "signature-cocktails",
    image: "/apple-cocktail-green.jpg",
    tags: ["Signature"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "signature-cocktail-4",
    name: "Sunset Shrine",
    price: 12000,
    currency: "NGN",
    description: "Tropical sunset flavors in a glass",
    category: "signature-cocktails",
    image: "/sunset-cocktail-orange-red.jpg",
    tags: ["Signature"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "signature-cocktail-5",
    name: "Red Island",
    price: 12000,
    currency: "NGN",
    description: "Vibrant red fruit cocktail with island spices",
    category: "signature-cocktails",
    image: "/red-tropical-cocktail.jpg",
    tags: ["Signature"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "signature-cocktail-6",
    name: "Wild Sex",
    price: 12000,
    currency: "NGN",
    description: "Bold and adventurous flavor combination",
    category: "signature-cocktails",
    image: "/exotic-cocktail-layered.jpg",
    tags: ["Signature"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "signature-cocktail-7",
    name: "Passion Paradise",
    price: 12000,
    currency: "NGN",
    description: "Tropical passion fruit paradise",
    category: "signature-cocktails",
    image: "/passion-fruit-tropical-cocktail.jpg",
    tags: ["Signature"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "signature-cocktail-8",
    name: "Hibiscus Twilight",
    price: 12000,
    currency: "NGN",
    description: "Floral hibiscus cocktail with evening notes",
    category: "signature-cocktails",
    image: "/hibiscus-flower-cocktail-purple.jpg",
    tags: ["Signature"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "signature-cocktail-9",
    name: "The Fourwings Royale",
    price: 12000,
    currency: "NGN",
    description: "House signature cocktail fit for royalty",
    category: "signature-cocktails",
    image: "/luxury-gold-cocktail-champagne.jpg",
    tags: ["Signature"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "signature-cocktail-10",
    name: "Sweet In The Middle",
    price: 12000,
    currency: "NGN",
    description: "Perfectly balanced sweetness",
    category: "signature-cocktails",
    image: "/sweet-colorful-cocktail.jpg",
    tags: ["Signature"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "signature-cocktail-11",
    name: "Mai Tai",
    price: 12000,
    currency: "NGN",
    description: "Rum, curaçao, orgeat syrup, and lime juice",
    category: "signature-cocktails",
    image: "/mai-tai-tiki-cocktail.jpg",
    tags: ["Signature"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "signature-cocktail-12",
    name: "Blue Hawaii",
    price: 12000,
    currency: "NGN",
    description:
      "Rum, vodka, blue curaçao, pineapple juice, and sweet and sour mix",
    category: "signature-cocktails",
    image: "/blue-hawaii-cocktail.jpg",
    tags: ["Signature"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "signature-cocktail-13",
    name: "Devil's Tail",
    price: 12000,
    currency: "NGN",
    description: "Spiced rum cocktail with a devilish twist",
    category: "signature-cocktails",
    image: "/devils-tail-cocktail.jpg",
    tags: ["Signature"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "mocktail-1",
    name: "Cucumber Mint Cooler",
    price: 10000,
    currency: "NGN",
    description: "Refreshing cucumber and mint mocktail",
    category: "signature-mocktails",
    image: "/cucumber-mint-mocktail.jpg",
    tags: ["Mocktail", "Non-Alcoholic"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "mocktail-2",
    name: "Tropical Blizz",
    price: 10000,
    currency: "NGN",
    description: "Tropical fruit blend",
    category: "signature-mocktails",
    image: "/tropical-fruit-mocktail.jpg",
    tags: ["Mocktail", "Non-Alcoholic"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "mocktail-3",
    name: "Lavender Crush",
    price: 10000,
    currency: "NGN",
    description: "Floral lavender mocktail",
    category: "signature-mocktails",
    image: "/lavender-mocktail.jpg",
    tags: ["Mocktail", "Non-Alcoholic"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "mocktail-4",
    name: "Evening Surprises",
    price: 10000,
    currency: "NGN",
    description: "Mysterious evening blend",
    category: "signature-mocktails",
    image: "/evening-mocktail.jpg",
    tags: ["Mocktail", "Non-Alcoholic"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "mocktail-5",
    name: "Fancy Nancy",
    price: 10000,
    currency: "NGN",
    description: "Elegant non-alcoholic cocktail",
    category: "signature-mocktails",
    image: "/fancy-mocktail.jpg",
    tags: ["Mocktail", "Non-Alcoholic"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "mocktail-6",
    name: "Coco Bong",
    price: 10000,
    currency: "NGN",
    description: "Coconut-based mocktail",
    category: "signature-mocktails",
    image: "/coconut-mocktail.jpg",
    tags: ["Mocktail", "Non-Alcoholic"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "mocktail-7",
    name: "Blue Sky Mojito",
    price: 12000,
    currency: "NGN",
    description: "Non-alcoholic mojito with blue curaçao syrup",
    category: "signature-mocktails",
    image: "/blue-mocktail-mojito.jpg",
    tags: ["Mocktail", "Non-Alcoholic"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "whiskey-1",
    name: "Macallan 15",
    price: 325000,
    currency: "NGN",
    description: "Premium single malt Scotch whisky aged 15 years",
    category: "whiskey",
    image: "/macallan-15-whiskey.jpg",
    tags: ["Whiskey", "Premium"],
    popular: false,
    availableIn: ["office"],
  },
  {
    id: "whiskey-2",
    name: "Glenfiddich 15yrs",
    price: 340000,
    currency: "NGN",
    description: "Smooth single malt Scotch whisky aged 15 years",
    category: "whiskey",
    image: "/glenfiddich-15-whiskey.jpg",
    tags: ["Whiskey", "Premium"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "whiskey-3",
    name: "Glenfiddich 18yrs",
    price: 400000,
    currency: "NGN",
    description: "Exceptional single malt Scotch whisky aged 18 years",
    category: "whiskey",
    image: "/glenfiddich-18-whiskey.jpg",
    tags: ["Whiskey", "Premium"],
    popular: true,
    availableIn: ["club", "office"],
  },
  {
    id: "whiskey-4",
    name: "Glenfiddich 21yrs",
    price: 1600000,
    currency: "NGN",
    description: "Rare single malt Scotch whisky aged 21 years",
    category: "whiskey",
    image: "/glenfiddich-21-whiskey.jpg",
    tags: ["Whiskey", "Premium", "Luxury"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "whiskey-5",
    name: "Glenfiddich 23yrs",
    price: 1730000,
    currency: "NGN",
    description: "Ultra-premium single malt Scotch whisky aged 23 years",
    category: "whiskey",
    image: "/glenfiddich-23-whiskey.jpg",
    tags: ["Whiskey", "Premium", "Luxury"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "whiskey-6",
    name: "Teeling Single Grain",
    price: 325000,
    currency: "NGN",
    description: "Irish single grain whiskey",
    category: "whiskey",
    image: "/teeling-single-grain-whiskey.jpg",
    tags: ["Whiskey", "Premium"],
    popular: false,
    availableIn: ["club"],
  },
  {
    id: "whiskey-7",
    name: "Teeling Single Malt",
    price: 415000,
    currency: "NGN",
    description: "Irish single malt whiskey",
    category: "whiskey",
    image: "/teeling-single-malt-whiskey.jpg",
    tags: ["Whiskey", "Premium"],
    popular: false,
    availableIn: ["club"],
  },
  {
    id: "whiskey-8",
    name: "Teeling Rising Reserve 21yrs",
    price: 985000,
    currency: "NGN",
    description: "Premium Irish whiskey aged 21 years",
    category: "whiskey",
    image: "/teeling-rising-reserve-21-whiskey.jpg",
    tags: ["Whiskey", "Premium", "Luxury"],
    popular: false,
    availableIn: ["club"],
  },
  {
    id: "whiskey-9",
    name: "Teeling Small Batch",
    price: 86000,
    currency: "NGN",
    description: "Small batch Irish whiskey",
    category: "whiskey",
    image: "/teeling-small-batch-whiskey.jpg",
    tags: ["Whiskey"],
    popular: false,
    availableIn: ["club"],
  },
  {
    id: "whiskey-10",
    name: "Macallan 15 (Club)",
    price: 585000,
    currency: "NGN",
    description: "Premium single malt Scotch whisky aged 15 years",
    category: "whiskey",
    image: "/macallan-15-whiskey.jpg",
    tags: ["Whiskey", "Premium"],
    popular: false,
    availableIn: ["club"],
  },
  {
    id: "cognac-1",
    name: "Bisquit & Dubouché VSOP",
    price: 225000,
    currency: "NGN",
    description: "Premium French cognac VSOP",
    category: "cognac",
    image: "/bisquit-cognac-vsop.jpg",
    tags: ["Cognac", "Premium"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "cognac-2",
    name: "Bisquit & Dubouché XO",
    price: 915000,
    currency: "NGN",
    description: "Luxury French cognac XO",
    category: "cognac",
    image: "/bisquit-cognac-xo.jpg",
    tags: ["Cognac", "Premium", "Luxury"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "cognac-3",
    name: "Hennessy VS",
    price: 250000,
    currency: "NGN",
    description: "Classic French cognac VS",
    category: "cognac",
    image: "/hennessy-vs-cognac.jpg",
    tags: ["Cognac", "Premium"],
    popular: true,
    availableIn: ["club", "office"],
  },
  {
    id: "cognac-4",
    name: "Hennessy VSOP",
    price: 305000,
    currency: "NGN",
    description: "Premium French cognac VSOP",
    category: "cognac",
    image: "/hennessy-vsop-cognac.jpg",
    tags: ["Cognac", "Premium"],
    popular: true,
    availableIn: ["club", "office"],
  },
  {
    id: "cognac-5",
    name: "Martell VS",
    price: 280000,
    currency: "NGN",
    description: "French cognac VS",
    category: "cognac",
    image: "/martell-vs-cognac.jpg",
    tags: ["Cognac", "Premium"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "cognac-6",
    name: "Martell Blue Swift",
    price: 285000,
    currency: "NGN",
    description: "French cognac finished in bourbon casks",
    category: "cognac",
    image: "/martell-blue-swift.jpg",
    tags: ["Cognac", "Premium"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "tequila-1",
    name: "Padre Azul Blanco",
    price: 357000,
    currency: "NGN",
    description: "Premium Mexican tequila blanco",
    category: "tequila",
    image: "/padre-azul-blanco.jpg",
    tags: ["Tequila", "Premium"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "tequila-2",
    name: "Padre Azul Reposado",
    price: 485000,
    currency: "NGN",
    description: "Premium Mexican tequila reposado",
    category: "tequila",
    image: "/padre-azul-reposado.jpg",
    tags: ["Tequila", "Premium"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "tequila-3",
    name: "Padre Azul Añejo",
    price: 525000,
    currency: "NGN",
    description: "Premium Mexican tequila añejo",
    category: "tequila",
    image: "/padre-azul-anejo.jpg",
    tags: ["Tequila", "Premium"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "tequila-4",
    name: "Salamanca",
    price: 300000,
    currency: "NGN",
    description: "Premium tequila",
    category: "tequila",
    image: "/salamanca-tequila.jpg",
    tags: ["Tequila", "Premium"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "tequila-5",
    name: "Casamigos Reposado",
    price: 390000,
    currency: "NGN",
    description: "Premium reposado tequila",
    category: "tequila",
    image: "/casamigos-reposado.jpg",
    tags: ["Tequila", "Premium"],
    popular: true,
    availableIn: ["club", "office"],
  },
  {
    id: "tequila-6",
    name: "818 Reposado",
    price: 300000,
    currency: "NGN",
    description: "Premium reposado tequila",
    category: "tequila",
    image: "/818-reposado-tequila-bottle.jpg",
    tags: ["Tequila", "Premium"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "champagne-1",
    name: "Veuve Rich",
    price: 400000,
    currency: "NGN",
    description: "Premium French champagne",
    category: "champagne",
    image: "/veuve-clicquot-rich-champagne.jpg",
    tags: ["Champagne", "Premium"],
    popular: false,
    availableIn: ["office"],
  },
  {
    id: "champagne-2",
    name: "Veuve Brut",
    price: 300000,
    currency: "NGN",
    description: "Classic French champagne brut",
    category: "champagne",
    image: "/veuve-clicquot-brut.jpg",
    tags: ["Champagne", "Premium"],
    popular: true,
    availableIn: ["office"],
  },
  {
    id: "champagne-3",
    name: "Moët Brut",
    price: 270000,
    currency: "NGN",
    description: "Classic French champagne brut",
    category: "champagne",
    image: "/moet-chandon-brut.jpg",
    tags: ["Champagne", "Premium"],
    popular: true,
    availableIn: ["office"],
  },
  {
    id: "champagne-4",
    name: "Moët Rosé",
    price: 375000,
    currency: "NGN",
    description: "Elegant French rosé champagne",
    category: "champagne",
    image: "/moet-chandon-rose-imperial-champagne.jpg",
    tags: ["Champagne", "Premium"],
    popular: false,
    availableIn: ["office"],
  },
  {
    id: "champagne-5",
    name: "Canard Brut",
    price: 225000,
    currency: "NGN",
    description: "French champagne brut",
    category: "champagne",
    image: "/canard-duchene-brut-champagne.jpg",
    tags: ["Champagne", "Premium"],
    popular: false,
    availableIn: ["office"],
  },
  {
    id: "champagne-6",
    name: "Canard Rosé",
    price: 285000,
    currency: "NGN",
    description: "French rosé champagne",
    category: "champagne",
    image: "/canard-duchene-rose-champagne.jpg",
    tags: ["Champagne", "Premium"],
    popular: false,
    availableIn: ["office"],
  },
  {
    id: "food-1",
    name: "Spicy Jumbo Prawn",
    price: 45000,
    currency: "NGN",
    description: "Jumbo prawns with spicy seasoning",
    category: "food",
    image: "/spicy-jumbo-prawns.jpg",
    tags: ["Seafood", "Spicy"],
    popular: true,
    availableIn: ["office"],
  },
  {
    id: "food-2",
    name: "Mixed Espetada",
    price: 40000,
    currency: "NGN",
    description: "Mixed meat skewers",
    category: "food",
    image: "/mixed-espetada-skewers.jpg",
    tags: ["Grilled", "Mixed"],
    popular: true,
    availableIn: ["office"],
  },
  {
    id: "food-3",
    name: "Chicken Laps & Fries",
    price: 25000,
    currency: "NGN",
    description: "Chicken drumsticks with french fries",
    category: "food",
    image: "/chicken-drumsticks-fries.jpg",
    tags: ["Chicken", "Fried"],
    popular: true,
    availableIn: ["office"],
  },
  {
    id: "food-4",
    name: "Peppered Snails with Veggies",
    price: 22000,
    currency: "NGN",
    description: "Spicy snails with vegetables",
    category: "food",
    image: "/peppered-snails-vegetables.jpg",
    tags: ["Snails", "Spicy"],
    popular: false,
    availableIn: ["office"],
  },
  {
    id: "food-5",
    name: "Fillet Steak",
    price: 35000,
    currency: "NGN",
    description: "Premium beef fillet steak",
    category: "food",
    image: "/beef-fillet-steak.jpg",
    tags: ["Beef", "Grilled"],
    popular: true,
    availableIn: ["office"],
  },
  {
    id: "food-6",
    name: "Perfectly Grilled Pork Ribs",
    price: 32000,
    currency: "NGN",
    description: "Tender grilled pork ribs",
    category: "food",
    image: "/grilled-pork-ribs.jpg",
    tags: ["Pork", "Grilled"],
    popular: true,
    availableIn: ["office"],
  },
  {
    id: "food-7",
    name: "Beef Espetada",
    price: 25000,
    currency: "NGN",
    description: "Seasoned with our homemade signature sauce",
    category: "food",
    image: "/beef-espetada.png",
    tags: ["Grilled", "Signature"],
    popular: false,
    availableIn: ["office", "club"],
  },
  {
    id: "food-8",
    name: "Beef or chicken Burger",
    price: 20000,
    currency: "NGN",
    description: "Perfectly grilled, topped with Mozzarella cheese",
    category: "food",
    image: "/beef-burger.png",
    tags: ["Burger", "Grilled"],
    popular: false,
    availableIn: ["office", "club"],
  },
  {
    id: "food-09",
    name: "Fourwinds Lion-man Platter",
    price: 80000,
    currency: "NGN",
    description:
      "Wings 10 / Snail 3 / Jumbo turkey 1 / Chicken laps 1 / Yam fries / Pepper sauce",
    category: "food",
    image: "/lionman-platter.png",
    tags: ["Platter", "Sharing", "Signature"],
    popular: true,
    availableIn: ["office", "club"],
  },
  {
    id: "club-food-1",
    name: "Grilled Prawns",
    price: 25000,
    currency: "NGN",
    description: "Fresh grilled prawns",
    category: "food",
    image: "/spicy-jumbo-prawns.jpg",
    tags: ["Seafood", "Grilled"],
    popular: true,
    availableIn: ["club"],
  },
  {
    id: "club-food-2",
    name: "Grilled Croaker Fish",
    price: 20000,
    currency: "NGN",
    description: "Whole grilled croaker fish",
    category: "food",
    image: "https://image.api.sportal365.com/process/smp-images-production/pulse.ng/27072024/f465d933-3521-4b2d-b302-b1a32f96c652?operations=autocrop(1200:630)",
    tags: ["Seafood", "Grilled"],
    popular: true,
    availableIn: ["club"],
  },
  {
    id: "club-food-3",
    name: "Special Grilled Pork Ribs",
    price: 35000,
    currency: "NGN",
    description: "Special grilled pork ribs",
    category: "food",
    image: "https://media.istockphoto.com/id/170439534/photo/grilled-pork.jpg?s=612x612&w=0&k=20&c=5_NBkVSlY0xLHWiNMGbCRONzrPJPWIoz6lOrH4UV_jA=",
    tags: ["Pork", "Grilled"],
    popular: true,
    availableIn: ["club"],
  },
  {
    id: "club-food-4",
    name: "West African Grilled Catfish",
    price: 19500,
    currency: "NGN",
    description: "Traditional grilled catfish",
    category: "food",
    image: "https://www.grillzville.com/wp-content/uploads/2023/10/catfish.jpg",
    tags: ["Seafood", "Grilled", "African"],
    popular: true,
    availableIn: ["club"],
  },
  {
    id: "club-food-5",
    name: "Grilled Guinea Fowl",
    price: 25000,
    currency: "NGN",
    description: "Grilled guinea fowl",
    category: "food",
    image: "https://foodschmooze.org/wp-content/uploads/2017/12/Lidia-Bastianich_Roasted-Guinea-Hen-with-Balsamic-Glaze_recipe.jpg",
    tags: ["Poultry", "Grilled"],
    popular: false,
    availableIn: ["club"],
  },
  {
    id: "club-food-6",
    name: "Jumbo Turkey",
    price: 12500,
    currency: "NGN",
    description: "Jumbo turkey portions",
    category: "food",
    image: "/grilled-jumbo-turkey-portions.jpg",
    tags: ["Poultry", "Grilled"],
    popular: false,
    availableIn: ["club"],
  },
  {
    id: "club-food-7",
    name: "Grilled Beef Steak",
    price: 22000,
    currency: "NGN",
    description: "Premium grilled beef steak",
    category: "food",
    image: "/premium-grilled-beef-steak.jpg",
    tags: ["Beef", "Grilled"],
    popular: true,
    availableIn: ["club"],
  },
  {
    id: "club-food-8",
    name: "Grilled Half Chicken",
    price: 15000,
    currency: "NGN",
    description: "Half chicken grilled",
    category: "food",
    image: "/grilled-half-chicken.jpg",
    tags: ["Chicken", "Grilled"],
    popular: true,
    availableIn: ["club"],
  },
  {
    id: "side-dish-1",
    name: "Smokey Jollof Rice",
    price: 5000,
    currency: "NGN",
    description: "Traditional Nigerian jollof rice",
    category: "sides",
    image: "/smokey-nigerian-jollof-rice.jpg",
    tags: ["Rice", "African"],
    popular: true,
    availableIn: ["club"],
  },
  {
    id: "side-dish-2",
    name: "Special Fried Rice",
    price: 6000,
    currency: "NGN",
    description: "Fried rice with vegetables",
    category: "sides",
    image: "/special-fried-rice-with-vegetables.jpg",
    tags: ["Rice"],
    popular: true,
    availableIn: ["club"],
  },
  {
    id: "side-dish-3",
    name: "White Rice",
    price: 5000,
    currency: "NGN",
    description: "Steamed white rice",
    category: "sides",
    image: "/steamed-white-rice.jpg",
    tags: ["Rice"],
    popular: false,
    availableIn: ["club"],
  },
  {
    id: "side-dish-4",
    name: "Stir-fry Spaghetti",
    price: 5500,
    currency: "NGN",
    description: "Stir-fried spaghetti",
    category: "sides",
    image: "/stir-fried-spaghetti-nigerian.jpg",
    tags: ["Pasta"],
    popular: false,
    availableIn: ["club"],
  },
  {
    id: "side-dish-5",
    name: "White Rice & Ofada Sauce",
    price: 7000,
    currency: "NGN",
    description: "White rice with traditional Ofada sauce",
    category: "sides",
    image: "/white-rice-with-ofada-sauce.jpg",
    tags: ["Rice", "African"],
    popular: false,
    availableIn: ["club"],
  },
  // {
  //   id: "soup-1",
  //   name: "Egusi",
  //   price: 10000,
  //   currency: "NGN",
  //   description: "Traditional Nigerian egusi soup",
  //   category: "soups",
  //   image: "/egusi.jpg",
  //   tags: ["Soup", "African"],
  //   popular: true,
  //   availableIn: ["club"],
  // },
  // {
  //   id: "soup-2",
  //   name: "Afang",
  //   price: 12000,
  //   currency: "NGN",
  //   description: "Traditional Nigerian afang soup",
  //   category: "soups",
  //   image: "/afang.jpg",
  //   tags: ["Soup", "African"],
  //   popular: false,
  //   availableIn: ["club"],
  // },
  // {
  //   id: "soup-3",
  //   name: "Vegetable Soup",
  //   price: 10000,
  //   currency: "NGN",
  //   description: "Nigerian vegetable soup",
  //   category: "soups",
  //   image: "/vegetable-soup.jpg",
  //   tags: ["Soup", "African"],
  //   popular: false,
  //   availableIn: ["club"],
  // },
  {
    id: "addon-1",
    name: "Coleslaw",
    price: 3000,
    currency: "NGN",
    description: "Fresh coleslaw",
    category: "add-ons",
    image: "/fresh-coleslaw-salad.jpg",
    tags: ["Side"],
    popular: true,
    availableIn: ["club"],
  },
  {
    id: "addon-2",
    name: "Fried Plantain",
    price: 3000,
    currency: "NGN",
    description: "Golden fried plantains",
    category: "add-ons",
    image: "/golden-fried-plantains.jpg",
    tags: ["Side"],
    popular: true,
    availableIn: ["club"],
  },
  {
    id: "addon-3",
    name: "Fried Yam",
    price: 3000,
    currency: "NGN",
    description: "Crispy fried yam",
    category: "add-ons",
    image: "/crispy-fried-yam.jpg",
    tags: ["Side"],
    popular: false,
    availableIn: ["club"],
  },
  {
    id: "addon-4",
    name: "French Fries",
    price: 3000,
    currency: "NGN",
    description: "Crispy french fries",
    category: "add-ons",
    image: "/french-fries.jpg",
    tags: ["Side"],
    popular: true,
    availableIn: ["club"],
  },
  {
    id: "addon-5",
    name: "Roasted Corn",
    price: 2500,
    currency: "NGN",
    description: "Roasted corn on the cob",
    category: "add-ons",
    image: "/roasted-corn.jpg",
    tags: ["Side"],
    popular: false,
    availableIn: ["club"],
  },
  {
    id: "addon-6",
    name: "Roasted Plantain",
    price: 2500,
    currency: "NGN",
    description: "Roasted plantains",
    category: "add-ons",
    image: "/roasted-plantain.jpg",
    tags: ["Side"],
    popular: false,
    availableIn: ["club"],
  },
  {
    id: "shot-1",
    name: "Tray of 18 Shots",
    price: 80000,
    currency: "NGN",
    description: "Tray of 18 assorted shots",
    category: "shots",
    image: "/tray-18-shots.jpg",
    tags: ["Tray", "Party"],
    popular: true,
    availableIn: ["office", "club"],
  },
  {
    id: "shot-2",
    name: "Tray of 12 Shots",
    price: 70000,
    currency: "NGN",
    description: "Tray of 12 assorted shots",
    category: "shots",
    image: "/tray-12-shots.jpg",
    tags: ["Tray", "Party"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "shot-3",
    name: "Tray of 6 Shots",
    price: 50000,
    currency: "NGN",
    description: "Tray of 6 assorted shots",
    category: "shots",
    image: "/tray-6-shots.jpg",
    tags: ["Tray"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "shot-4",
    name: "Tray of 2 Shots",
    price: 30000,
    currency: "NGN",
    description: "Tray of 2 assorted shots",
    category: "shots",
    image: "/tray-2-shots.jpg",
    tags: ["Tray"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "shot-5",
    name: "Sierra Shot",
    price: 10000,
    currency: "NGN",
    description: "Single Sierra shot",
    category: "shots",
    image: "/sierra-shot.jpg",
    tags: ["Single"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "shot-6",
    name: "Salamacha Shot",
    price: 20000,
    currency: "NGN",
    description: "Single Salamacha shot",
    category: "shots",
    image: "/salamacha-shot.jpg",
    tags: ["Single", "Premium"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
  id: "soup-1",
  name: "Egusi",
  price: 10000,
  currency: "NGN",
  description: "Traditional Nigerian egusi soup served with any swallow of your choice: Eba, Semo, Poundo (Add Chicken ₦7,000 / Add Fish ₦6,000)",
  category: "soups",
  image: "/egusi.jpg",
  tags: ["Soup", "African"],
  popular: true,
  availableIn: ["club"],
},
{
  id: "soup-2",
  name: "Afang",
  price: 12000,
  currency: "NGN",
  description: "Traditional Nigerian afang soup served with any swallow of your choice: Eba, Semo, Poundo (Add Chicken ₦7,000 / Add Fish ₦6,000)",
  category: "soups",
  image: "/afang.jpg",
  tags: ["Soup", "African"],
  popular: false,
  availableIn: ["club"],
},
{
  id: "soup-3",
  name: "Vegetable Soup",
  price: 10000,
  currency: "NGN",
  description: "Nigerian vegetable soup served with any swallow of your choice: Eba, Semo, Poundo (Add Chicken ₦7,000 / Add Fish ₦6,000)",
  category: "soups",
  image: "/vegetable-soup.jpg",
  tags: ["Soup", "African"],
  popular: false,
  availableIn: ["club"],
},
{
  id: "beer-1",
  name: "Big Stout",
  price: 4000,
  currency: "NGN",
  description: "Premium stout beer",
  category: "beer",
  image: "https://images.unsplash.com/photo-1720110919165-49df0e4f5d49?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fHN0b3V0fGVufDB8fDB8fHww",
  tags: ["Beer", "Stout"],
  popular: false,
  availableIn: ["club", "office"],
},
{
  id: "beer-2",
  name: "Small Stout",
  price: 3000,
  currency: "NGN",
  description: "Classic stout beer",
  category: "beer",
  image: "https://images.unsplash.com/photo-1720110919165-49df0e4f5d49?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fHN0b3V0fGVufDB8fDB8fHww",
  tags: ["Beer", "Stout"],
  popular: false,
  availableIn: ["club", "office"],
},
{
  id: "beer-3",
  name: "Heineken",
  price: 4000,
  currency: "NGN",
  description: "Premium lager beer",
  category: "beer",
  image: "https://images.unsplash.com/photo-1618885472179-5e474019f2a9?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aGVpbmVrZW58ZW58MHx8MHx8fDA%3D",
  tags: ["Beer", "Lager"],
  popular: true,
  availableIn: ["club", "office"],
},
{
  id: "beer-4",
  name: "Big Star",
  price: 3000,
  currency: "NGN",
  description: "Nigerian lager beer",
  category: "beer",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1LdzUAb4zuLigU-KCi39To1d5eOkGrUb8-g&s",
  tags: ["Beer", "Lager"],
  popular: false,
  availableIn: ["club", "office"],
},
{
  id: "beer-5",
  name: "Trophy",
  price: 3000,
  currency: "NGN",
  description: "Nigerian lager beer",
  category: "beer",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPYQIaBEsV-_V0hBFbYXpQyr3Fi5FZM6h2qw&s",
  tags: ["Beer", "Lager"],
  popular: false,
  availableIn: ["club", "office"],
},
{
  id: "beer-6",
  name: "Gulder",
  price: 3000,
  currency: "NGN",
  description: "Nigerian lager beer",
  category: "beer",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWY08oF68JJ_9vBDwmC3PEowshC-CQBYUT-g&s",
  tags: ["Beer", "Lager"],
  popular: false,
  availableIn: ["club", "office"],
},
{
  id: "beer-7",
  name: "Star Radler",
  price: 3000,
  currency: "NGN",
  description: "Lemon flavored beer",
  category: "beer",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRqIMXiwE91Q7yXXHgmE-qyxlSWWHWeKkV3A&s",
  tags: ["Beer", "Radler"],
  popular: false,
  availableIn: ["club", "office"],
},
{
  id: "beer-8",
  name: "Goldberg",
  price: 3000,
  currency: "NGN",
  description: "Nigerian lager beer",
  category: "beer",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSViUozO1kdx0rRYgAy_MoJIwhiWSq3rWbI9g&s",
  tags: ["Beer", "Lager"],
  popular: false,
  availableIn: ["club", "office"],
},
{
  id: "beer-9",
  name: "Origin",
  price: 4000,
  currency: "NGN",
  description: "Premium Nigerian beer",
  category: "beer",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdE95r1s82oJstBMxzqVNS-crFzR68dKxInw&s",
  tags: ["Beer", "Premium"],
  popular: false,
  availableIn: ["club", "office"],
},
{
  id: "beer-10",
  name: "Desperado",
  price: 4000,
  currency: "NGN",
  description: "Tequila flavored beer",
  category: "beer",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS17t5sUhHfwWUFSfPxC2NynwNbEyyvalNhOg&s",
  tags: ["Beer", "Flavored"],
  popular: false,
  availableIn: ["club", "office"],
},
{
  id: "beer-11",
  name: "Budweiser",
  price: 4000,
  currency: "NGN",
  description: "American lager beer",
  category: "beer",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQGQEcTs0iHWmeiWrQrYZ3uI_bmzBO9Nyqo-A&s",
  tags: ["Beer", "Lager"],
  popular: true,
  availableIn: ["club", "office"],
},
// SOFT DRINKS
{
  id: "soft-drink-1",
  name: "Coke",
  price: 2000,
  currency: "NGN",
  description: "Coca-Cola soft drink",
  category: "soft-drinks",
  image: "https://t4.ftcdn.net/jpg/02/84/65/61/360_F_284656117_sPF8gVWaX627bq5qKrlrvCz1eFfowdBf.jpg",
  tags: ["Soft Drink", "Cola"],
  popular: true,
  availableIn: ["club", "office"],
},
{
  id: "soft-drink-2",
  name: "Fanta",
  price: 2000,
  currency: "NGN",
  description: "Orange flavored soft drink",
  category: "soft-drinks",
  image: "https://media.istockphoto.com/id/521463520/photo/fanta-splash.jpg?s=612x612&w=0&k=20&c=t8J_SFh-SrH5XJe95yTQxd7_Ws1MfIUVRNzdIf1Wr0k=",
  tags: ["Soft Drink", "Orange"],
  popular: true,
  availableIn: ["club", "office"],
},
{
  id: "soft-drink-3",
  name: "Sprite",
  price: 2000,
  currency: "NGN",
  description: "Lemon-lime flavored soft drink",
  category: "soft-drinks",
  image: "https://mir-s3-cdn-cf.behance.net/projects/404/25f402135347067.Y3JvcCwzNDAyLDI2NjAsMCwxMDk.jpg",
  tags: ["Soft Drink", "Lemon-Lime"],
  popular: true,
  availableIn: ["club", "office"],
},
{
  id: "soft-drink-4",
  name: "Malta Guinness",
  price: 2000,
  currency: "NGN",
  description: "Non-alcoholic malt drink",
  category: "soft-drinks",
  image: "https://myafricanshop.co.uk/wp-content/uploads/2024/11/Malta-Guinness-AD.png",
  tags: ["Soft Drink", "Malt"],
  popular: true,
  availableIn: ["club", "office"],
},
{
  id: "soft-drink-5",
  name: "Bitter Lemon",
  price: 2000,
  currency: "NGN",
  description: "Schweppes bitter lemon drink",
  category: "soft-drinks",
  image: "https://thumbs.dreamstime.com/b/viersen-germany-may-close-up-yellow-schweppes-indian-tonic-water-bottle-container-selective-focus-center-182606299.jpg",
  tags: ["Soft Drink", "Lemon"],
  popular: false,
  availableIn: ["club", "office"],
},
{
  id: "soft-drink-6",
  name: "Virgin Mojito",
  price: 2000,
  currency: "NGN",
  description: "Schweppes virgin mojito",
  category: "soft-drinks",
  image: "https://i.pinimg.com/736x/57/cd/dd/57cddd925ee9c23164c2cfb69faf0e92.jpg",
  tags: ["Soft Drink", "Mojito"],
  popular: false,
  availableIn: ["club", "office"],
},
{
  id: "soft-drink-7",
  name: "Chapman",
  price: 2000,
  currency: "NGN",
  description: "Schweppes chapman drink",
  category: "soft-drinks",
  image: "https://www.dashofjazz.com/wp-content/uploads/2024/10/Dash-of-Jazz-Nigerian-Chapman-Drink-5.jpg",
  tags: ["Soft Drink", "Chapman"],
  popular: false,
  availableIn: ["club", "office"],
},
{
  id: "soft-drink-8",
  name: "Tonic Water",
  price: 2000,
  currency: "NGN",
  description: "Schweppes tonic water",
  category: "soft-drinks",
  image: "https://www.shutterstock.com/image-photo/minsk-belarus-september-27-2019-260nw-1515697967.jpg",
  tags: ["Soft Drink", "Tonic"],
  popular: false,
  availableIn: ["club", "office"],
},
{
  id: "soft-drink-9",
  name: "Soda Water",
  price: 2000,
  currency: "NGN",
  description: "Schweppes soda water",
  category: "soft-drinks",
  image: "https://www.shutterstock.com/image-photo/kiev-ukraine-august-06-2021-260nw-2022259904.jpg",
  tags: ["Soft Drink", "Soda"],
  popular: false,
  availableIn: ["club", "office"],
},

// WATER
{
  id: "water-1",
  name: "Bottled Water (Big)",
  price: 2000,
  currency: "NGN",
  description: "Large bottled water",
  category: "water",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTE218lHhiogulAACANyYiT3tO1R5YsNhOqeg&s",
  tags: ["Water"],
  popular: true,
  availableIn: ["club", "office"],
},
{
  id: "water-2",
  name: "Bottled Water (Small)",
  price: 1500,
  currency: "NGN",
  description: "Small bottled water",
  category: "water",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTE218lHhiogulAACANyYiT3tO1R5YsNhOqeg&s",
  tags: ["Water"],
  popular: true,
  availableIn: ["club", "office"],
},
{
  id: "water-3",
  name: "Sparkling Water",
  price: 2500,
  currency: "NGN",
  description: "Carbonated sparkling water",
  category: "water",
  image: "https://img.freepik.com/free-photo/front-view-glass-soda-full-dark-drink-photo-champagne-xmas-water_140725-93014.jpg?semt=ais_hybrid&w=740&q=80",
  tags: ["Water", "Sparkling"],
  popular: false,
  availableIn: ["club", "office"],
},
{
  id: "water-4",
  name: "Soda Water",
  price: 2000,
  currency: "NGN",
  description: "Carbonated soda water",
  category: "water",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXhVd83bwBBfl0O4eLs8XOKs40QF-Ezs_0ZA&s",
  tags: ["Water", "Carbonated"],
  popular: false,
  availableIn: ["club", "office"],
},
{
  id: "water-5",
  name: "Tonic Water",
  price: 2000,
  currency: "NGN",
  description: "Tonic water with quinine",
  category: "water",
  image: "https://www.deliciousmagazine.co.uk/wp-content/uploads/2014/01/tonic-water.jpg",
  tags: ["Water", "Tonic"],
  popular: false,
  availableIn: ["club", "office"],
},
// SUYA
{
  id: "suya-1",
  name: "Guinea Fowl Suya",
  price: 25000,
  currency: "NGN",
  description: "Whole guinea fowl grilled with spicy suya spices",
  category: "suya",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNMwRR8uRgexJtd8L4uQu9O-6wzH4bWONbZA&s",
  tags: ["Suya", "Grilled", "Poultry"],
  popular: true,
  availableIn: ["club"],
},
{
  id: "suya-2",
  name: "Full Chicken Suya",
  price: 22000,
  currency: "NGN",
  description: "Whole chicken grilled with traditional suya spices",
  category: "suya",
  image: "https://janeicesavors.com/wp-content/uploads/2022/05/whole-chicken-suya-e1710353038817.jpg",
  tags: ["Suya", "Grilled", "Chicken"],
  popular: true,
  availableIn: ["club"],
},
{
  id: "suya-3",
  name: "Ram Suya",
  price: 2000,
  currency: "NGN",
  description: "Spicy grilled ram meat on skewers",
  category: "suya",
  image: "https://afrosuyapalace.com/wp-content/uploads/2024/11/kebab.jpg",
  tags: ["Suya", "Grilled", "Ram"],
  popular: false,
  availableIn: ["club"],
},
{
  id: "suya-4",
  name: "Beef Suya",
  price: 1000,
  currency: "NGN",
  description: "Traditional beef suya on skewers with yaji spice",
  category: "suya",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqUaneLaMjcaHj-MN3Ihrt6lkHsB3EayyufQ&s",
  tags: ["Suya", "Grilled", "Beef"],
  popular: true,
  availableIn: ["club"],
},
{
  id: "suya-5",
  name: "Kidney Suya",
  price: 1000,
  currency: "NGN",
  description: "Grilled kidney with suya spices",
  category: "suya",
  image: "https://afrosuyapalace.com/wp-content/uploads/2024/11/kidney-suya.jpg",
  tags: ["Suya", "Grilled", "Offal"],
  popular: false,
  availableIn: ["club"],
},
{
  id: "suya-6",
  name: "Stripe Suya",
  price: 1000,
  currency: "NGN",
  description: "Grilled tripe with suya spices",
  category: "suya",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuVREcVdgrK4DLuwZ9WeFT7g78PHqE7JZU9w&s",
  tags: ["Suya", "Grilled", "Offal"],
  popular: false,
  availableIn: ["club"],
},

// SHAWARMA
{
  id: "shawarma-1",
  name: "Chicken Shawarma",
  price: 10000,
  currency: "NGN",
  description: "Grilled chicken wrapped in pita with vegetables and sauce",
  category: "shawarma",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXyGiSZj2wMrLY2Vunl5EbjTmYUAAgXqcLEA&s",
  tags: ["Shawarma", "Chicken", "Wrap"],
  popular: true,
  availableIn: ["club"],
},
{
  id: "shawarma-2",
  name: "Beef Shawarma",
  price: 12000,
  currency: "NGN",
  description: "Grilled beef wrapped in pita with vegetables and sauce",
  category: "shawarma",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFG2qVSfpbyJkWLn5KkmL0TmCmDb4tx_x8bg&s",
  tags: ["Shawarma", "Beef", "Wrap"],
  popular: true,
  availableIn: ["club"],
},
{
  id: "shawarma-3",
  name: "Ram Suya Shawarma",
  price: 14000,
  currency: "NGN",
  description: "Spicy ram suya wrapped in pita with vegetables",
  category: "shawarma",
  image: "https://media.istockphoto.com/id/171591106/photo/chicken-souvlaki-wrap.jpg?s=612x612&w=0&k=20&c=ysTWdd6oCdiVCUJZ0leyNIGj6H2MuJ9ogWuMRP-GCTs=",
  tags: ["Shawarma", "Ram", "Wrap"],
  popular: false,
  availableIn: ["club"],
},
{
  id: "shawarma-4",
  name: "Mixed Shawarma",
  price: 15000,
  currency: "NGN",
  description: "Combination of chicken and beef wrapped in pita",
  category: "shawarma",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpcFuSqt1H4knm5cdnapZtevX8YQPU_UURAg&sx`",
  tags: ["Shawarma", "Mixed", "Wrap"],
  popular: true,
  availableIn: ["club"],
},
{
  id: "shisha-1",
  name: "Strawberry Flavor",
  price: 25000,
  currency: "NGN",
  description: "Premium strawberry flavored shisha",
  category: "shisha",
  image: "https://media.istockphoto.com/id/1151734258/photo/fruit-smoking-hookah.jpg?s=612x612&w=0&k=20&c=-6u3FcURmbHEVoZe_BWFkcbKbBDt8KlOJWZhzUMSevg=",
  tags: ["Shisha", "Fruit"],
  popular: true,
  availableIn: ["club"],
},
{
  id: "shisha-2",
  name: "Mint Flavor",
  price: 25000,
  currency: "NGN",
  description: "Refreshing mint flavored shisha",
  category: "shisha",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUDImiBwDfwXyJkdLc-j4Rs5umROusT14gnw&s",
  tags: ["Shisha", "Mint"],
  popular: true,
  availableIn: ["club"],
},
{
  id: "shisha-3",
  name: "Mojito Flavor",
  price: 25000,
  currency: "NGN",
  description: "Cool mojito flavored shisha",
  category: "shisha",
  image: "https://www.shutterstock.com/image-photo/hookah-shisha-glass-mojito-cocktail-600nw-1960215040.jpg",
  tags: ["Shisha", "Mojito"],
  popular: true,
  availableIn: ["club"],
},
{
  id: "shisha-4",
  name: "Lemon Flavor",
  price: 25000,
  currency: "NGN",
  description: "Zesty lemon flavored shisha",
  category: "shisha",
  image: "https://img.freepik.com/premium-photo/smoking-hookah-with-lemon-flavor_75924-10673.jpg",
  tags: ["Shisha", "Citrus"],
  popular: false,
  availableIn: ["club"],
},
{
  id: "shisha-5",
  name: "Apple Flavor",
  price: 25000,
  currency: "NGN",
  description: "Sweet apple flavored shisha",
  category: "shisha",
  image: "/shisha-apple-flavor.jpghttps://st3.depositphotos.com/1704325/16386/i/450/depositphotos_163868844-stock-photo-tobacco-hookah-on-apple-tobacco.jpg",
  tags: ["Shisha", "Fruit"],
  popular: true,
  availableIn: ["club"],
},
{
  id: "shisha-6",
  name: "Love 66",
  price: 25000,
  currency: "NGN",
  description: "Love 66 premium shisha blend",
  category: "shisha",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRGGV97639Gl_TdVqyPOEKkXBIPvhAch8Oww&s",
  tags: ["Shisha", "Special"],
  popular: false,
  availableIn: ["club"],
},
{
  id: "shisha-7",
  name: "Kiwi",
  price: 25000,
  currency: "NGN",
  description: "Exotic kiwi flavored shisha",
  category: "shisha",
  image: "https://thumbs.dreamstime.com/b/cake-2545348.jpg",
  tags: ["Shisha", "Fruit"],
  popular: false,
  availableIn: ["club"],
},
{
  id: "shisha-8",
  name: "Watermelon",
  price: 25000,
  currency: "NGN",
  description: "Fresh watermelon flavored shisha",
  category: "shisha",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOCxKPnLTnftrI-E26naOlb6GaM3Fd8OeEKg&s",
  tags: ["Shisha", "Fruit"],
  popular: true,
  availableIn: ["club"],
},
{
  id: "shisha-9",
  name: "Grape",
  price: 25000,
  currency: "NGN",
  description: "Rich grape flavored shisha",
  category: "shisha",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCQYhsGOSrzI6Ibl39etc-7mumORuQCALo1g&s",
  tags: ["Shisha", "Fruit"],
  popular: false,
  availableIn: ["club"],
},
{
  id: "shisha-10",
  name: "Any Two Flavors Mix",
  price: 25000,
  currency: "NGN",
  description: "Mix any two flavors of your choice",
  category: "shisha",
  image: "https://shishahub.net/wp-content/uploads/2025/05/Shisha-cafe-10.png",
  tags: ["Shisha", "Custom", "Mixed"],
  popular: true,
  availableIn: ["club"],
},
];

export const categoryDisplayNames: Record<string, string> = {
  cocktails: "Cocktails",
  "signature-cocktails": "Signature Cocktails",
  "signature-mocktails": "Signature Mocktails",
  whiskey: "Whiskey",
  cognac: "Cognac",
  tequila: "Tequila",
  champagne: "Champagne",
  shots: "Shots",
  shisha: "Shisha",
  beer: "Beer",
  "soft-drinks": "Soft & Energy Drinks",
  water: "Water",
  food: "Food",
  sides: "Side Dishes",
  soups: "Soups",
  "add-ons": "Add-ons",
    suya: "Suya",
  shawarma: "Shawarma",
};
