import type { Drink } from "./types";

export const drinks: Drink[] = [
  {
    id: "cocktail-1",
    name: "Whiskey Sour",
    price: 10000,
    currency: "NGN",
    description:
      "Classic whiskey cocktail with fresh lemon juice and simple syrup",
    category: "cocktails",
    image: "/whiskey-sour-cocktail.jpg",
    tags: ["Cocktail", "Classic"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "cocktail-2",
    name: "Margarita",
    price: 10000,
    currency: "NGN",
    description: "Tequila, lime juice, and orange liqueur served chilled",
    category: "cocktails",
    image: "/margarita-cocktail.png",
    tags: ["Cocktail", "Classic"],
    popular: true,
    availableIn: ["club", "office"],
  },
  {
    id: "cocktail-3",
    name: "Mojito",
    price: 10000,
    currency: "NGN",
    description: "Refreshing blend of white rum, mint, lime, sugar, and soda",
    category: "cocktails",
    image: "/mojito-cocktail-with-mint.jpg",
    tags: ["Cocktail", "Classic"],
    popular: true,
    availableIn: ["club", "office"],
  },
  {
    id: "cocktail-4",
    name: "Long Island",
    price: 12000,
    currency: "NGN",
    description: "Bold mix of multiple spirits with cola and citrus notes",
    category: "cocktails",
    image: "/long-island-iced-tea.jpg",
    tags: ["Cocktail", "Classic"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "cocktail-5",
    name: "Old Fashioned",
    price: 12000,
    currency: "NGN",
    description: "Timeless whiskey cocktail with bitters and sugar",
    category: "cocktails",
    image: "/old-fashioned-cocktail.png",
    tags: ["Cocktail", "Classic"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "cocktail-6",
    name: "Pornstar Martini",
    price: 10000,
    currency: "NGN",
    description: "Vodka, passion fruit liqueur, vanilla, and passion fruit",
    category: "cocktails",
    image: "/pornstar-martini-passion-fruit.jpg",
    tags: ["Cocktail", "Classic"],
    popular: true,
    availableIn: ["club", "office"],
  },
  {
    id: "cocktail-7",
    name: "Classic Martini",
    price: 10000,
    currency: "NGN",
    description: "Gin and dry vermouth, garnished with an olive or lemon twist",
    category: "cocktails",
    image: "/classic-martini-cocktail.jpg",
    tags: ["Cocktail", "Classic"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "cocktail-8",
    name: "Bellini",
    price: 10000,
    currency: "NGN",
    description: "Prosecco and peach purée",
    category: "cocktails",
    image: "/bellini-peach-cocktail.jpg",
    tags: ["Cocktail", "Classic"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "signature-cocktail-1",
    name: "Atlantic Cocktail",
    price: 150000,
    currency: "NGN",
    description: "Premium signature cocktail with exotic ingredients",
    category: "signature-cocktails",
    image: "/luxury-premium-cocktail.jpg",
    tags: ["Signature", "Premium"],
    popular: true,
    availableIn: ["club", "office"],
  },
  {
    id: "signature-cocktail-2",
    name: "The Century",
    price: 12000,
    currency: "NGN",
    description: "Signature blend celebrating timeless flavors",
    category: "signature-cocktails",
    image: "/signature-cocktail-gold.jpg",
    tags: ["Signature"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "signature-cocktail-3",
    name: "Apple Savanna",
    price: 12000,
    currency: "NGN",
    description: "Fresh apple infusion with savanna notes",
    category: "signature-cocktails",
    image: "/apple-cocktail-green.jpg",
    tags: ["Signature"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "signature-cocktail-4",
    name: "Sunset Shrine",
    price: 12000,
    currency: "NGN",
    description: "Tropical sunset flavors in a glass",
    category: "signature-cocktails",
    image: "/sunset-cocktail-orange-red.jpg",
    tags: ["Signature"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "signature-cocktail-5",
    name: "Red Island",
    price: 12000,
    currency: "NGN",
    description: "Vibrant red fruit cocktail with island spices",
    category: "signature-cocktails",
    image: "/red-tropical-cocktail.jpg",
    tags: ["Signature"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "signature-cocktail-6",
    name: "Wild Sex",
    price: 12000,
    currency: "NGN",
    description: "Bold and adventurous flavor combination",
    category: "signature-cocktails",
    image: "/exotic-cocktail-layered.jpg",
    tags: ["Signature"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "signature-cocktail-7",
    name: "Passion Paradise",
    price: 12000,
    currency: "NGN",
    description: "Tropical passion fruit paradise",
    category: "signature-cocktails",
    image: "/passion-fruit-tropical-cocktail.jpg",
    tags: ["Signature"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "signature-cocktail-8",
    name: "Hibiscus Twilight",
    price: 12000,
    currency: "NGN",
    description: "Floral hibiscus cocktail with evening notes",
    category: "signature-cocktails",
    image: "/hibiscus-flower-cocktail-purple.jpg",
    tags: ["Signature"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "signature-cocktail-9",
    name: "The Fourwings Royale",
    price: 12000,
    currency: "NGN",
    description: "House signature cocktail fit for royalty",
    category: "signature-cocktails",
    image: "/luxury-gold-cocktail-champagne.jpg",
    tags: ["Signature"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "signature-cocktail-10",
    name: "Sweet In The Middle",
    price: 12000,
    currency: "NGN",
    description: "Perfectly balanced sweetness",
    category: "signature-cocktails",
    image: "/sweet-colorful-cocktail.jpg",
    tags: ["Signature"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "signature-cocktail-11",
    name: "Mai Tai",
    price: 12000,
    currency: "NGN",
    description: "Rum, curaçao, orgeat syrup, and lime juice",
    category: "signature-cocktails",
    image: "/mai-tai-tiki-cocktail.jpg",
    tags: ["Signature"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "signature-cocktail-12",
    name: "Blue Hawaii",
    price: 12000,
    currency: "NGN",
    description:
      "Rum, vodka, blue curaçao, pineapple juice, and sweet and sour mix",
    category: "signature-cocktails",
    image: "/blue-hawaii-cocktail.jpg",
    tags: ["Signature"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "signature-cocktail-13",
    name: "Devil's Tail",
    price: 12000,
    currency: "NGN",
    description: "Spiced rum cocktail with a devilish twist",
    category: "signature-cocktails",
    image: "/devils-tail-cocktail.jpg",
    tags: ["Signature"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "mocktail-1",
    name: "Cucumber Mint Cooler",
    price: 10000,
    currency: "NGN",
    description: "Refreshing cucumber and mint mocktail",
    category: "signature-mocktails",
    image: "/cucumber-mint-mocktail.jpg",
    tags: ["Mocktail", "Non-Alcoholic"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "mocktail-2",
    name: "Tropical Blizz",
    price: 10000,
    currency: "NGN",
    description: "Tropical fruit blend",
    category: "signature-mocktails",
    image: "/tropical-fruit-mocktail.jpg",
    tags: ["Mocktail", "Non-Alcoholic"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "mocktail-3",
    name: "Lavender Crush",
    price: 10000,
    currency: "NGN",
    description: "Floral lavender mocktail",
    category: "signature-mocktails",
    image: "/lavender-mocktail.jpg",
    tags: ["Mocktail", "Non-Alcoholic"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "mocktail-4",
    name: "Evening Surprises",
    price: 10000,
    currency: "NGN",
    description: "Mysterious evening blend",
    category: "signature-mocktails",
    image: "/evening-mocktail.jpg",
    tags: ["Mocktail", "Non-Alcoholic"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "mocktail-5",
    name: "Fancy Nancy",
    price: 10000,
    currency: "NGN",
    description: "Elegant non-alcoholic cocktail",
    category: "signature-mocktails",
    image: "/fancy-mocktail.jpg",
    tags: ["Mocktail", "Non-Alcoholic"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "mocktail-6",
    name: "Coco Bong",
    price: 10000,
    currency: "NGN",
    description: "Coconut-based mocktail",
    category: "signature-mocktails",
    image: "/coconut-mocktail.jpg",
    tags: ["Mocktail", "Non-Alcoholic"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "mocktail-7",
    name: "Blue Sky Mojito",
    price: 12000,
    currency: "NGN",
    description: "Non-alcoholic mojito with blue curaçao syrup",
    category: "signature-mocktails",
    image: "/blue-mocktail-mojito.jpg",
    tags: ["Mocktail", "Non-Alcoholic"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "whiskey-1",
    name: "Macallan 15",
    price: 325000,
    currency: "NGN",
    description: "Premium single malt Scotch whisky aged 15 years",
    category: "whiskey",
    image: "/macallan-15-whiskey.jpg",
    tags: ["Whiskey", "Premium"],
    popular: false,
    availableIn: ["office"],
  },
  {
    id: "whiskey-2",
    name: "Glenfiddich 15yrs",
    price: 340000,
    currency: "NGN",
    description: "Smooth single malt Scotch whisky aged 15 years",
    category: "whiskey",
    image: "/glenfiddich-15-whiskey.jpg",
    tags: ["Whiskey", "Premium"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "whiskey-3",
    name: "Glenfiddich 18yrs",
    price: 400000,
    currency: "NGN",
    description: "Exceptional single malt Scotch whisky aged 18 years",
    category: "whiskey",
    image: "/glenfiddich-18-whiskey.jpg",
    tags: ["Whiskey", "Premium"],
    popular: true,
    availableIn: ["club", "office"],
  },
  {
    id: "whiskey-4",
    name: "Glenfiddich 21yrs",
    price: 1600000,
    currency: "NGN",
    description: "Rare single malt Scotch whisky aged 21 years",
    category: "whiskey",
    image: "/glenfiddich-21-whiskey.jpg",
    tags: ["Whiskey", "Premium", "Luxury"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "whiskey-5",
    name: "Glenfiddich 23yrs",
    price: 1730000,
    currency: "NGN",
    description: "Ultra-premium single malt Scotch whisky aged 23 years",
    category: "whiskey",
    image: "/glenfiddich-23-whiskey.jpg",
    tags: ["Whiskey", "Premium", "Luxury"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "whiskey-6",
    name: "Teeling Single Grain",
    price: 325000,
    currency: "NGN",
    description: "Irish single grain whiskey",
    category: "whiskey",
    image: "/teeling-single-grain-whiskey.jpg",
    tags: ["Whiskey", "Premium"],
    popular: false,
    availableIn: ["club"],
  },
  {
    id: "whiskey-7",
    name: "Teeling Single Malt",
    price: 415000,
    currency: "NGN",
    description: "Irish single malt whiskey",
    category: "whiskey",
    image: "/teeling-single-malt-whiskey.jpg",
    tags: ["Whiskey", "Premium"],
    popular: false,
    availableIn: ["club"],
  },
  {
    id: "whiskey-8",
    name: "Teeling Rising Reserve 21yrs",
    price: 985000,
    currency: "NGN",
    description: "Premium Irish whiskey aged 21 years",
    category: "whiskey",
    image: "/teeling-rising-reserve-21-whiskey.jpg",
    tags: ["Whiskey", "Premium", "Luxury"],
    popular: false,
    availableIn: ["club"],
  },
  {
    id: "whiskey-9",
    name: "Teeling Small Batch",
    price: 86000,
    currency: "NGN",
    description: "Small batch Irish whiskey",
    category: "whiskey",
    image: "/teeling-small-batch-whiskey.jpg",
    tags: ["Whiskey"],
    popular: false,
    availableIn: ["club"],
  },
  {
    id: "whiskey-10",
    name: "Macallan 15 (Club)",
    price: 585000,
    currency: "NGN",
    description: "Premium single malt Scotch whisky aged 15 years",
    category: "whiskey",
    image: "/macallan-15-whiskey.jpg",
    tags: ["Whiskey", "Premium"],
    popular: false,
    availableIn: ["club"],
  },
  {
    id: "cognac-1",
    name: "Bisquit & Dubouché VSOP",
    price: 225000,
    currency: "NGN",
    description: "Premium French cognac VSOP",
    category: "cognac",
    image: "/bisquit-cognac-vsop.jpg",
    tags: ["Cognac", "Premium"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "cognac-2",
    name: "Bisquit & Dubouché XO",
    price: 915000,
    currency: "NGN",
    description: "Luxury French cognac XO",
    category: "cognac",
    image: "/bisquit-cognac-xo.jpg",
    tags: ["Cognac", "Premium", "Luxury"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "cognac-3",
    name: "Hennessy VS",
    price: 250000,
    currency: "NGN",
    description: "Classic French cognac VS",
    category: "cognac",
    image: "/hennessy-vs-cognac.jpg",
    tags: ["Cognac", "Premium"],
    popular: true,
    availableIn: ["club", "office"],
  },
  {
    id: "cognac-4",
    name: "Hennessy VSOP",
    price: 305000,
    currency: "NGN",
    description: "Premium French cognac VSOP",
    category: "cognac",
    image: "/hennessy-vsop-cognac.jpg",
    tags: ["Cognac", "Premium"],
    popular: true,
    availableIn: ["club", "office"],
  },
  {
    id: "cognac-5",
    name: "Martell VS",
    price: 280000,
    currency: "NGN",
    description: "French cognac VS",
    category: "cognac",
    image: "/martell-vs-cognac.jpg",
    tags: ["Cognac", "Premium"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "cognac-6",
    name: "Martell Blue Swift",
    price: 285000,
    currency: "NGN",
    description: "French cognac finished in bourbon casks",
    category: "cognac",
    image: "/martell-blue-swift.jpg",
    tags: ["Cognac", "Premium"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "tequila-1",
    name: "Padre Azul Blanco",
    price: 357000,
    currency: "NGN",
    description: "Premium Mexican tequila blanco",
    category: "tequila",
    image: "/padre-azul-blanco.jpg",
    tags: ["Tequila", "Premium"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "tequila-2",
    name: "Padre Azul Reposado",
    price: 485000,
    currency: "NGN",
    description: "Premium Mexican tequila reposado",
    category: "tequila",
    image: "/padre-azul-reposado.jpg",
    tags: ["Tequila", "Premium"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "tequila-3",
    name: "Padre Azul Añejo",
    price: 525000,
    currency: "NGN",
    description: "Premium Mexican tequila añejo",
    category: "tequila",
    image: "/padre-azul-anejo.jpg",
    tags: ["Tequila", "Premium"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "tequila-4",
    name: "Salamanca",
    price: 300000,
    currency: "NGN",
    description: "Premium tequila",
    category: "tequila",
    image: "/salamanca-tequila.jpg",
    tags: ["Tequila", "Premium"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "tequila-5",
    name: "Casamigos Reposado",
    price: 390000,
    currency: "NGN",
    description: "Premium reposado tequila",
    category: "tequila",
    image: "/casamigos-reposado.jpg",
    tags: ["Tequila", "Premium"],
    popular: true,
    availableIn: ["club", "office"],
  },
  {
    id: "tequila-6",
    name: "818 Reposado",
    price: 300000,
    currency: "NGN",
    description: "Premium reposado tequila",
    category: "tequila",
    image: "/818-reposado-tequila-bottle.jpg",
    tags: ["Tequila", "Premium"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "champagne-1",
    name: "Veuve Rich",
    price: 400000,
    currency: "NGN",
    description: "Premium French champagne",
    category: "champagne",
    image: "/veuve-clicquot-rich-champagne.jpg",
    tags: ["Champagne", "Premium"],
    popular: false,
    availableIn: ["office"],
  },
  {
    id: "champagne-2",
    name: "Veuve Brut",
    price: 300000,
    currency: "NGN",
    description: "Classic French champagne brut",
    category: "champagne",
    image: "/veuve-clicquot-brut.jpg",
    tags: ["Champagne", "Premium"],
    popular: true,
    availableIn: ["office"],
  },
  {
    id: "champagne-3",
    name: "Moët Brut",
    price: 270000,
    currency: "NGN",
    description: "Classic French champagne brut",
    category: "champagne",
    image: "/moet-chandon-brut.jpg",
    tags: ["Champagne", "Premium"],
    popular: true,
    availableIn: ["office"],
  },
  {
    id: "champagne-4",
    name: "Moët Rosé",
    price: 375000,
    currency: "NGN",
    description: "Elegant French rosé champagne",
    category: "champagne",
    image: "/moet-chandon-rose-imperial-champagne.jpg",
    tags: ["Champagne", "Premium"],
    popular: false,
    availableIn: ["office"],
  },
  {
    id: "champagne-5",
    name: "Canard Brut",
    price: 225000,
    currency: "NGN",
    description: "French champagne brut",
    category: "champagne",
    image: "/canard-duchene-brut-champagne.jpg",
    tags: ["Champagne", "Premium"],
    popular: false,
    availableIn: ["office"],
  },
  {
    id: "champagne-6",
    name: "Canard Rosé",
    price: 285000,
    currency: "NGN",
    description: "French rosé champagne",
    category: "champagne",
    image: "/canard-duchene-rose-champagne.jpg",
    tags: ["Champagne", "Premium"],
    popular: false,
    availableIn: ["office"],
  },
  {
    id: "food-1",
    name: "Spicy Jumbo Prawn",
    price: 45000,
    currency: "NGN",
    description: "Jumbo prawns with spicy seasoning",
    category: "food",
    image: "/spicy-jumbo-prawns.jpg",
    tags: ["Seafood", "Spicy"],
    popular: true,
    availableIn: ["office"],
  },
  {
    id: "food-2",
    name: "Mixed Espetada",
    price: 40000,
    currency: "NGN",
    description: "Mixed meat skewers",
    category: "food",
    image: "/mixed-espetada-skewers.jpg",
    tags: ["Grilled", "Mixed"],
    popular: true,
    availableIn: ["office"],
  },
  {
    id: "food-3",
    name: "Chicken Laps & Fries",
    price: 25000,
    currency: "NGN",
    description: "Chicken drumsticks with french fries",
    category: "food",
    image: "/chicken-drumsticks-fries.jpg",
    tags: ["Chicken", "Fried"],
    popular: true,
    availableIn: ["office"],
  },
  {
    id: "food-4",
    name: "Peppered Snails with Veggies",
    price: 22000,
    currency: "NGN",
    description: "Spicy snails with vegetables",
    category: "food",
    image: "/peppered-snails-vegetables.jpg",
    tags: ["Snails", "Spicy"],
    popular: false,
    availableIn: ["office"],
  },
  {
    id: "food-5",
    name: "Fillet Steak",
    price: 35000,
    currency: "NGN",
    description: "Premium beef fillet steak",
    category: "food",
    image: "/beef-fillet-steak.jpg",
    tags: ["Beef", "Grilled"],
    popular: true,
    availableIn: ["office"],
  },
  {
    id: "food-6",
    name: "Perfectly Grilled Pork Ribs",
    price: 32000,
    currency: "NGN",
    description: "Tender grilled pork ribs",
    category: "food",
    image: "/grilled-pork-ribs.jpg",
    tags: ["Pork", "Grilled"],
    popular: true,
    availableIn: ["office"],
  },
  {
    id: "food-7",
    name: "Beef Espetada",
    price: 25000,
    currency: "NGN",
    description: "Seasoned with our homemade signature sauce",
    category: "food",
    image: "/beef-espetada.png",
    tags: ["Grilled", "Signature"],
    popular: false,
    availableIn: ["office", "club"],
  },
  {
    id: "food-8",
    name: "Beef or chicken Burger",
    price: 20000,
    currency: "NGN",
    description: "Perfectly grilled, topped with Mozzarella cheese",
    category: "food",
    image: "/beef-burger.png",
    tags: ["Burger", "Grilled"],
    popular: false,
    availableIn: ["office", "club"],
  },
  {
    id: "food-09",
    name: "Fourwinds Lion-man Platter",
    price: 80000,
    currency: "NGN",
    description:
      "Wings 10 / Snail 3 / Jumbo turkey 1 / Chicken laps 1 / Yam fries / Pepper sauce",
    category: "food",
    image: "/lionman-platter.png",
    tags: ["Platter", "Sharing", "Signature"],
    popular: true,
    availableIn: ["office", "club"],
  },
  {
    id: "club-food-1",
    name: "Grilled Prawns",
    price: 25000,
    currency: "NGN",
    description: "Fresh grilled prawns",
    category: "food",
    image: "/spicy-jumbo-prawns.jpg",
    tags: ["Seafood", "Grilled"],
    popular: true,
    availableIn: ["club"],
  },
  {
    id: "club-food-2",
    name: "Grilled Croaker Fish",
    price: 20000,
    currency: "NGN",
    description: "Whole grilled croaker fish",
    category: "food",
    image: "/placeholder.svg?height=400&width=400",
    tags: ["Seafood", "Grilled"],
    popular: true,
    availableIn: ["club"],
  },
  {
    id: "club-food-3",
    name: "Special Grilled Pork Ribs",
    price: 35000,
    currency: "NGN",
    description: "Special grilled pork ribs",
    category: "food",
    image: "/placeholder.svg?height=400&width=400",
    tags: ["Pork", "Grilled"],
    popular: true,
    availableIn: ["club"],
  },
  {
    id: "club-food-4",
    name: "West African Grilled Catfish",
    price: 19500,
    currency: "NGN",
    description: "Traditional grilled catfish",
    category: "food",
    image: "/placeholder.svg?height=400&width=400",
    tags: ["Seafood", "Grilled", "African"],
    popular: true,
    availableIn: ["club"],
  },
  {
    id: "club-food-5",
    name: "Grilled Guinea Fowl",
    price: 25000,
    currency: "NGN",
    description: "Grilled guinea fowl",
    category: "food",
    image: "/placeholder.svg?height=400&width=400",
    tags: ["Poultry", "Grilled"],
    popular: false,
    availableIn: ["club"],
  },
  {
    id: "club-food-6",
    name: "Jumbo Turkey",
    price: 12500,
    currency: "NGN",
    description: "Jumbo turkey portions",
    category: "food",
    image: "/grilled-jumbo-turkey-portions.jpg",
    tags: ["Poultry", "Grilled"],
    popular: false,
    availableIn: ["club"],
  },
  {
    id: "club-food-7",
    name: "Grilled Beef Steak",
    price: 22000,
    currency: "NGN",
    description: "Premium grilled beef steak",
    category: "food",
    image: "/premium-grilled-beef-steak.jpg",
    tags: ["Beef", "Grilled"],
    popular: true,
    availableIn: ["club"],
  },
  {
    id: "club-food-8",
    name: "Grilled Half Chicken",
    price: 15000,
    currency: "NGN",
    description: "Half chicken grilled",
    category: "food",
    image: "/grilled-half-chicken.jpg",
    tags: ["Chicken", "Grilled"],
    popular: true,
    availableIn: ["club"],
  },
  {
    id: "side-dish-1",
    name: "Smokey Jollof Rice",
    price: 5000,
    currency: "NGN",
    description: "Traditional Nigerian jollof rice",
    category: "sides",
    image: "/smokey-nigerian-jollof-rice.jpg",
    tags: ["Rice", "African"],
    popular: true,
    availableIn: ["club"],
  },
  {
    id: "side-dish-2",
    name: "Special Fried Rice",
    price: 6000,
    currency: "NGN",
    description: "Fried rice with vegetables",
    category: "sides",
    image: "/special-fried-rice-with-vegetables.jpg",
    tags: ["Rice"],
    popular: true,
    availableIn: ["club"],
  },
  {
    id: "side-dish-3",
    name: "White Rice",
    price: 5000,
    currency: "NGN",
    description: "Steamed white rice",
    category: "sides",
    image: "/steamed-white-rice.jpg",
    tags: ["Rice"],
    popular: false,
    availableIn: ["club"],
  },
  {
    id: "side-dish-4",
    name: "Stir-fry Spaghetti",
    price: 5500,
    currency: "NGN",
    description: "Stir-fried spaghetti",
    category: "sides",
    image: "/stir-fried-spaghetti-nigerian.jpg",
    tags: ["Pasta"],
    popular: false,
    availableIn: ["club"],
  },
  {
    id: "side-dish-5",
    name: "White Rice & Ofada Sauce",
    price: 7000,
    currency: "NGN",
    description: "White rice with traditional Ofada sauce",
    category: "sides",
    image: "/white-rice-with-ofada-sauce.jpg",
    tags: ["Rice", "African"],
    popular: false,
    availableIn: ["club"],
  },
  {
    id: "soup-1",
    name: "Egusi",
    price: 10000,
    currency: "NGN",
    description: "Traditional Nigerian egusi soup",
    category: "soups",
    image: "/traditional-nigerian-egusi-soup.jpg",
    tags: ["Soup", "African"],
    popular: true,
    availableIn: ["club"],
  },
  {
    id: "soup-2",
    name: "Afang",
    price: 12000,
    currency: "NGN",
    description: "Traditional Nigerian afang soup",
    category: "soups",
    image: "/traditional-nigerian-afang-soup.jpg",
    tags: ["Soup", "African"],
    popular: false,
    availableIn: ["club"],
  },
  {
    id: "soup-3",
    name: "Vegetable Soup",
    price: 10000,
    currency: "NGN",
    description: "Nigerian vegetable soup",
    category: "soups",
    image: "/nigerian-vegetable-soup.jpg",
    tags: ["Soup", "African"],
    popular: false,
    availableIn: ["club"],
  },
  {
    id: "addon-1",
    name: "Coleslaw",
    price: 3000,
    currency: "NGN",
    description: "Fresh coleslaw",
    category: "add-ons",
    image: "/fresh-coleslaw-salad.jpg",
    tags: ["Side"],
    popular: true,
    availableIn: ["club"],
  },
  {
    id: "addon-2",
    name: "Fried Plantain",
    price: 3000,
    currency: "NGN",
    description: "Golden fried plantains",
    category: "add-ons",
    image: "/golden-fried-plantains.jpg",
    tags: ["Side"],
    popular: true,
    availableIn: ["club"],
  },
  {
    id: "addon-3",
    name: "Fried Yam",
    price: 3000,
    currency: "NGN",
    description: "Crispy fried yam",
    category: "add-ons",
    image: "/crispy-fried-yam.jpg",
    tags: ["Side"],
    popular: false,
    availableIn: ["club"],
  },
  {
    id: "addon-4",
    name: "French Fries",
    price: 3000,
    currency: "NGN",
    description: "Crispy french fries",
    category: "add-ons",
    image: "/crispy-golden-french-fries.jpg",
    tags: ["Side"],
    popular: true,
    availableIn: ["club"],
  },
  {
    id: "addon-5",
    name: "Roasted Corn",
    price: 2500,
    currency: "NGN",
    description: "Roasted corn on the cob",
    category: "add-ons",
    image: "/roasted-corn-on-cob.jpg",
    tags: ["Side"],
    popular: false,
    availableIn: ["club"],
  },
  {
    id: "addon-6",
    name: "Roasted Plantain",
    price: 2500,
    currency: "NGN",
    description: "Roasted plantains",
    category: "add-ons",
    image: "/roasted-plantains.jpg",
    tags: ["Side"],
    popular: false,
    availableIn: ["club"],
  },
  {
    id: "shot-1",
    name: "Tray of 18 Shots",
    price: 80000,
    currency: "NGN",
    description: "Tray of 18 assorted shots",
    category: "shots",
    image: "/tray-18-shots.jpg",
    tags: ["Tray", "Party"],
    popular: true,
    availableIn: ["office", "club"],
  },
  {
    id: "shot-2",
    name: "Tray of 12 Shots",
    price: 70000,
    currency: "NGN",
    description: "Tray of 12 assorted shots",
    category: "shots",
    image: "/tray-12-shots.jpg",
    tags: ["Tray", "Party"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "shot-3",
    name: "Tray of 6 Shots",
    price: 50000,
    currency: "NGN",
    description: "Tray of 6 assorted shots",
    category: "shots",
    image: "/tray-6-shots.jpg",
    tags: ["Tray"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "shot-4",
    name: "Tray of 2 Shots",
    price: 30000,
    currency: "NGN",
    description: "Tray of 2 assorted shots",
    category: "shots",
    image: "/tray-2-shots.jpg",
    tags: ["Tray"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "shot-5",
    name: "Sierra Shot",
    price: 10000,
    currency: "NGN",
    description: "Single Sierra shot",
    category: "shots",
    image: "/sierra-shot.jpg",
    tags: ["Single"],
    popular: false,
    availableIn: ["club", "office"],
  },
  {
    id: "shot-6",
    name: "Salamacha Shot",
    price: 20000,
    currency: "NGN",
    description: "Single Salamacha shot",
    category: "shots",
    image: "/salamacha-shot.jpg",
    tags: ["Single", "Premium"],
    popular: false,
    availableIn: ["club", "office"],
  },
];

export const categoryDisplayNames: Record<string, string> = {
  cocktails: "Cocktails",
  "signature-cocktails": "Signature Cocktails",
  "signature-mocktails": "Signature Mocktails",
  whiskey: "Whiskey",
  cognac: "Cognac",
  tequila: "Tequila",
  champagne: "Champagne",
  shots: "Shots",
  shisha: "Shisha",
  beer: "Beer",
  "soft-drinks": "Soft & Energy Drinks",
  water: "Water",
  food: "Food",
  sides: "Side Dishes",
  soups: "Soups",
  "add-ons": "Add-ons",
};
